#!/bin/bash
docker build -t rpslk-backend:latest rpslk-game/backend/.
docker build -t rpslk-frontend:latest rpslk-game/frontend/.

docker build -t vm-backend:latest vending-machine/backend/.
docker build -t vm-frontend:latest vending-machine/frontend/.
