apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-manager 
---          
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-management
rules:
  - apiGroups: ["apps"]
    resources: 
      - deployments 
      - deployments/scale
    verbs:
      - get
      - list 
      - watch
      - update
      - patch
  - apiGroups: [""]
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-controller
subjects:
- kind: ServiceAccount
  name: deploy-manager
  apiGroup: ""
roleRef:
  kind: Role
  name: deploy-management
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-manager-nodes-readonly
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-manager-nodes-readonly-binding
subjects:
  - kind: ServiceAccount
    name: deploy-manager
    namespace: default
roleRef:
  kind: ClusterRole
  name: deploy-manager-nodes-readonly
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-backend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: vm-backend
  template:
    metadata:
      labels:
        app: vm-backend
    spec:
      serviceAccountName: deploy-manager
      containers:
        - name: vm-backend
          image: vm-backend-distroless:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: FLASK_ENV
              value: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vm-frontend
  template:
    metadata:
      labels:
        app: vm-frontend
    spec:
      containers:
        - name: vm-frontend
          image: bgvm-vm-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vm-frontend
spec:
  selector:
    app: vm-frontend
  ports:
    - name: http
      port: 8080
      targetPort: 80
  type: NodePort 
---
apiVersion: v1
kind: Service
metadata: 
  name: vm-backend
spec:
  selector:
    app: vm-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 
