---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-backend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: vm-backend
  template:
    metadata:
      labels:
        app: vm-backend
    spec:
      containers:
        - name: vm-backend
          image: vm-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: FLASK_ENV
              value: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-frontend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: vm-frontend
  template:
    metadata:
      labels:
        app: vm-frontend
    spec:
      containers:
        - name: vm-frontend
          image: vm-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vm-frontend
spec:
  selector:
    app: vm-frontend
  ports:
    - name: http
      port: 8080
      targetPort: 80
  type: NodePort 
---
apiVersion: v1
kind: Service
metadata: 
  name: vm-backend
spec:
  selector:
    app: vm-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
