---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpslk-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rpslk-backend
  template:
    metadata:
      labels:
        app: rpslk-backend
    spec:
      containers:
        - name: rpslk-backend
          image: rpslk-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: FLASK_ENV
              value: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpslk-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rpslk-frontend
  template:
    metadata:
      labels:
        app: rpslk-frontend
    spec:
      containers:
        - name: rpslk-frontend
          image: rpslk-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rpslk-frontend
spec:
  selector:
    app: rpslk-frontend
  ports:
    - name: http
      port: 8080
      targetPort: 80
  type: NodePort 
---
apiVersion: v1
kind: Service
metadata: 
  name: rpslk-backend
spec:
  selector:
    app: rpslk-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
